name: build

on:
  push:
    branches: [main, master]
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Platformio
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile the project
        run: pio run -e release

      - name: Release
        if: ${{ github.event_name == 'release' }}
        id: release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set env
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Release project
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: .pio/build/release/firmware.bin
          asset_name: ${{ env.REPOSITORY_NAME }}-${{ env.GITHUB_TAG }}.bin
          asset_content_type: application/octet-stream

